apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-proxy
  template:
    metadata:
      labels:
        app: sensor-proxy
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: argoproj/sensor-proxy:latest
        name: sensor-proxy
        volumeMounts:
        - name: auth-volume
          mountPath: "/etc/sensor-proxy/"
      volumes:
      - name: auth-volume
        secret:
          secretName: sensor-proxy-auth-screts
          items:
          - key: auth-secrets
            path: auth-secrets.yaml
      serviceAccountName: argo-events-sa
